### ISSUE TITLE
参数量和内存占用之间的矛盾

### ISSUE THREAD

**Issue by zcode86** [qiulinzhang/SPConv.pytorch#10]
我发现将普通卷积替换成SPConv后，尽管参数量大大降低，但是对内存的占用极不友好。原先参数量1.9e+7，16G显卡batch-size可以设置48，替换后参数量1.13e+7，但是batch-size只能设置成24。想问一下作者，这个是什么原因？

**Comment by qiulinzhang** [comment]
多谢关注，原因是这样的，后面在特征生成的时候，上下两路的输出通道是都是一样的，从框架图上也可以看到，后面融合的时候是直接相加的，因此上下两路就需要保存2份NCHW，因此显存占用量会增加，SKNet也是有这样的问题，现在正在着手解决这个问题
