### ISSUE TITLE
在使用spconv代替传统conv2d时遇到了问题

### ISSUE THREAD

**Issue by jzw0707** [qiulinzhang/SPConv.pytorch#11]
请教一下将spconv应用于图像超分辨率中代替传统的conv2d时pycharm报错index 0 is out of bounds for dimension 0 with size 0，暂时找不到修改原因，请教一下如何修改？

**Comment by qiulinzhang** [comment]
具体是哪一行报错？可以贴一下完整的报错信息吗？

**Comment by jzw0707** [comment]
感谢您的回复，由于个人疏忽导致的报错信息对您造成打扰感到抱歉，非常棒的工作
