### ISSUE TITLE
替换dwconv

### ISSUE THREAD

**Issue by czy112** [qiulinzhang/SPConv.pytorch#12]
您好，请问如何用spconv替换dw类型的conv？

和通道相同的groups数目如何加入在spconv中？

**Comment by qiulinzhang** [comment]
https://github.com/qiulinzhang/SPConv.pytorch/blob/78c734f61e0b9bd5146239db4a668fcd7c45a4c8/code/resnet_sp.py#L23
这个地方可以修改groups，直接进行替换DW就可以

**Comment by qiulinzhang** [comment]
因为这里会将input_channel分成两部分，如果直接将Inverted residual 的groups放进去会导致groups比input_channel要多，因此在self.gwc里面的groups设置为self.inplane_3x3就可以了
