### ISSUE TITLE
redundancy 问题

### ISSUE THREAD

**Issue by qdd1234** [qiulinzhang/SPConv.pytorch#13]
您好，关于您论文中的SPConv，您对输入特征分成两个部分，一个部分是有效地，一个是冗余，就是怎么判定分成的一个部分是有效一个冗余的，为何a乘以Cin部分就是有效的？

**Comment by qiulinzhang** [comment]
> 您好，关于您论文中的SPConv，您对输入特征分成两个部分，一个部分是有效地，一个是冗余，就是怎么判定分成的一个部分是有效一个冗余的，为何a乘以Cin部分就是有效的？

多谢关注，我们最开始是使用一些规则比如L1Norm或者SE的结构去判断某个特征层是否重要，但是实验发现这样的人工干预效果较差，于是就直接对整个输入特征图进行分离，让上半部分特征图使用3x3的卷积核，让下半部分使用1x1的卷积核，由于3x3的卷积核和1x1的卷积核的感受野不一样，特征提取能力不一样，因此让网络自己去学习该把什么样的特征归结到3x3的卷积核，其他的归结到1x1的卷积核，这样子取得了较好的效果。
