### ISSUE TITLE
关于FER2013数据集在SPResNet18_CA上的精度问题

### ISSUE THREAD

**Issue by thgpddl** [qiulinzhang/SPConv.pytorch#15]
你好，我在阅读你的paper时，看到关于FER2013数据集精度有以下两个表述，我想知道的是为什么两周不一样？我应当以哪一个为准？

![H{K}$PR1O@KS6JJ}G UMPOL](https://user-images.githubusercontent.com/48787805/134798113-7333564f-d3aa-49ba-a9a9-e15034f0a2dd.png)
![image](https://user-images.githubusercontent.com/48787805/134798170-92b729c3-77ae-48bd-ae8f-34c7ab8420ce.png)

**Comment by qiulinzhang** [comment]
Hello 请问是不是弄错了？这个表格并不是我paper里面的

**Comment by thgpddl** [comment]
哈哈哈，我发现是的，我在看一篇论文：陈加敏，徐杨．基于注意力拆分卷积残差网络的表情识别[J/OL]．激光与光电子学进展. https://kns.cnki.net/kcms/detail/31.1690.TN.20210816.1121.016.html 这篇论文中引用了你的论文，即SPConv的相关部分。十分感谢你的回复(*^_^*)。
