### ISSUE TITLE
resnet_sp.py文件

### ISSUE THREAD

**Issue by xlh1135355585** [qiulinzhang/SPConv.pytorch#4]
48行：out_3x3_ratio = self.avgpool_add_3(out_3x3).squeeze()
56行：out_1x1_ratio = self.avgpool_add_1(out_1x1).squeeze()
squeeze()中是哪一维度？请作者说明。

**Comment by qiulinzhang** [comment]
![image](https://user-images.githubusercontent.com/34431846/87275315-656cd000-c510-11ea-9374-4d6a4467c1be.png)

https://pytorch.org/docs/master/generated/torch.squeeze.html

当不提供dim时，默认是把所有的维度为1的都给squeeze掉，也就是avgpool出来的NxCx1x1, 即HW维度

**Comment by xlh1135355585** [comment]
但是，如果把所有的维度为1的都给squeeze掉，只剩下一个维度。
在58行：out_31_ratio = torch.stack((out_3x3_ratio, out_1x1_ratio), 2)  会出现如下的报错：
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)。
该错误是因为维度超出了。

**Comment by xlh1135355585** [comment]
谢谢作者。明白了，但是如果batch为1的话就只剩一下一个维度了，希望作者可以完善下这一块的程序。

**Comment by qiulinzhang** [comment]
单张图片的话确实就会出问题了，多谢，我修改一下

**Comment by scutlrr** [comment]
`     out_3x3_ratio = self.avgpool_add_3(out_3x3).squeeze()`
  `     out_1x1_ratio = self.avgpool_add_1(out_1x1).squeeze()`
 `      out_31_ratio = torch.stack((out_3x3_ratio, out_1x1_ratio), 2)`
squeeze只剩下（N,C），为什么是在dim=2 stack呢

**Comment by xlh1135355585** [comment]
为了进行下面的softmax()，通俗来说就是stack成双通道算出来系数。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiulinzhang/SPConv.pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 晚上7:29
收件人:&nbsp;"qiulinzhang/SPConv.pytorch"<SPConv.pytorch@noreply.github.com&gt;;
抄送:&nbsp;"未来"<1135355585@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [qiulinzhang/SPConv.pytorch] resnet_sp.py文件 (#4)





 
     out_3x3_ratio = self.avgpool_add_3(out_3x3).squeeze()
      out_1x1_ratio = self.avgpool_add_1(out_1x1).squeeze()
       out_31_ratio = torch.stack((out_3x3_ratio, out_1x1_ratio), 2)
 squeeze只剩下（N,C），为什么是在dim=2 stack呢

**Comment by xlh1135355585** [comment]
> ` out_3x3_ratio = self.avgpool_add_3(out_3x3).squeeze()`
> ` out_1x1_ratio = self.avgpool_add_1(out_1x1).squeeze()`
> ` out_31_ratio = torch.stack((out_3x3_ratio, out_1x1_ratio), 2)`
> squeeze只剩下（N,C），为什么是在dim=2 stack呢

因为squeeze以后变成了两个维度了，所以在第三维也就是dim=2的地方进行stack。

**Comment by xlh1135355585** [comment]
> > ` out_3x3_ratio = self.avgpool_add_3(out_3x3).squeeze()`
> > ` out_1x1_ratio = self.avgpool_add_1(out_1x1).squeeze()`
> > ` out_31_ratio = torch.stack((out_3x3_ratio, out_1x1_ratio), 2)`
> > squeeze只剩下（N,C），为什么是在dim=2 stack呢
> 
> 因为squeeze以后变成了两个维度了，所以在第三维也就是dim=2的地方进行stack。

squeeze后维度为（batch，N*C)

**Comment by scutlrr** [comment]
谢谢，明白了。之前没理解好torch.stack的用法 @xlh1135355585
