### ISSUE TITLE
local variable 'x_1x1_se' referenced before assignment

### ISSUE THREAD

**Issue by qq957681892** [qiulinzhang/SPConv.pytorch#5]
首先感谢您的工作以及开源精神。我调用了训练脚本，报了标题所示的错误。看了下是resnet_sp.py的forward函数的里的问题
1.52和53行，x_1x1_se这个变量没有定义。后续也没有使用这个变量。
2.我把这行注释掉了，又在62行这里报了错：The size of tensor a (56) must match the size of tensor b (28) at non-singleton dimension 3

所以是不是这个forward函数，您哪里写错了？

**Comment by qiulinzhang** [comment]
不好意思，那里写错了，多谢指正，已经改正，重新下载代码就可以

**Comment by qq957681892** [comment]
好的，谢谢
