### ISSUE TITLE
Example for resnet18?

### ISSUE THREAD

**Issue by mozpp** [qiulinzhang/SPConv.pytorch#6]
如果注重轻量化的话，更应该写一个spconv基于resnet18的demo吧？
如果把spconv加到resnet中，要怎么加呢？

**Comment by qiulinzhang** [comment]
resnet_sp.py上写的是3x3的卷积替换，SpConv_3x3用来替换conv3x3，因此在basic block中对conv3x3进行替换即可，对比bottleneck 里面的替换

**Comment by mozpp** [comment]
> resnet_sp.py上写的是3x3的卷积替换，SpConv_3x3用来替换conv3x3，因此在basic block中对conv3x3进行替换即可，对比bottleneck 里面的替换

不不不，我直接替换会报错，有些细节不匹配的。我现在强行把self.stride设置为1才可行。

**Comment by qiulinzhang** [comment]
> > resnet_sp.py上写的是3x3的卷积替换，SpConv_3x3用来替换conv3x3，因此在basic block中对conv3x3进行替换即可，对比bottleneck 里面的替换
> 
> 不不不，我直接替换会报错，有些细节不匹配的。我现在强行把self.stride设置为1才可行。

可以贴一下错误吗 我这边是正常的

**Comment by mozpp** [comment]
> > > resnet_sp.py上写的是3x3的卷积替换，SpConv_3x3用来替换conv3x3，因此在basic block中对conv3x3进行替换即可，对比bottleneck 里面的替换
> > 
> > 
> > 不不不，我直接替换会报错，有些细节不匹配的。我现在强行把self.stride设置为1才可行。
> 
> 可以贴一下错误吗 我这边是正常的

大概的错误是 out+=residual 时，out和residual的大小不匹配，residual多下采样了一次。
我把stride写死成1之后解决了。

**Comment by qiulinzhang** [comment]
> > > > resnet_sp.py上写的是3x3的卷积替换，SpConv_3x3用来替换conv3x3，因此在basic block中对conv3x3进行替换即可，对比bottleneck 里面的替换
> > > 
> > > 
> > > 不不不，我直接替换会报错，有些细节不匹配的。我现在强行把self.stride设置为1才可行。
> > 
> > 
> > 可以贴一下错误吗 我这边是正常的
> 
> 大概的错误是 out+=residual 时，out和residual的大小不匹配，residual多下采样了一次。
> 我把stride写死成1之后解决了。

我这边就是直接把basicblock里面的两个3x3进行替换，然后参数不用动，是可以正常跑的，
已经修改，你那边重新下载调用应该就可以了
