### ISSUE TITLE
检测速度问题

### ISSUE THREAD

**Issue by rui19950830** [qiulinzhang/SPConv.pytorch#7]
你好，我在mmdetection的resnet的backbone中使用了SPConv，使用resnet50为主干网络的faster-rcnn进行训练和推断。在推断时发现使用SPConv后，推断时间反而变长了，使用常规卷积，测一张图需要0.04s左右，使用SPConv后，测一张图需要0.07s左右，这是什么原因呢

**Comment by yangzhaojason** [comment]
我在imagenet上面测试，对比标准的r50，推理速度下降了；但是我怀疑应该增强有一定的推理速度的影响

**Comment by qiulinzhang** [comment]
多谢指出，我在这边测试了，也发现了这个问题，我在论文中是按照其他论文的惯例，用的是batch-size为64，得到的推理速度比res50 baseline稍高，然后我又测试了一下mmdetection,确实发现推理速度降低了，原因是mmdetection的推理batch_size是1，同时我又测试了batch_size为1的imagenet 推理，发现速度确实是不如baseline，差不多慢了一倍
这里的猜想是：
- 当batch_size比较小时，比如1，2，4，GPU的算力并没有被完全调动起来，SPConv的小操作会比baseline消耗更多的时间用于内存数据读取等，内存读取相比较与算力时间是比较大的
- 而当batch_size比较大，比如64，GPU的算力被完全调动起来时，内存读取相比较于算力时间就比较小了

**Comment by rui19950830** [comment]
好的，非常感谢
